# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
