# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorie_nom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='nom_slug',
        ),
    ]
