# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_categorie_nom_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=200)),
                ('parution', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
    ]
