# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171015_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedpost',
            name='parution',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
