# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-01-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171018_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lien', models.TextField()),
                ('lienHttp', models.TextField()),
            ],
        ),
    ]
