# Generated by Django 2.0.2 on 2018-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='les_moins',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='les_pour',
            field=models.TextField(blank=True),
        ),
    ]
