# Generated by Django 2.0.2 on 2018-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_jv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jv',
            field=models.BooleanField(default=1),
        ),
    ]
