# Generated by Django 2.0.2 on 2018-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180217_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jv',
            field=models.BooleanField(default=0),
        ),
    ]
