# Generated by Django 2.0.2 on 2018-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180217_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jv',
            field=models.BooleanField(default=None),
        ),
    ]
