# Generated by Django 2.0.2 on 2018-02-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180217_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='jv',
        ),
    ]
