# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-02-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180217_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
